credentials:
  usernames:
    michael:
      email: michael@gmail.com
      name: Michael
      password: "$2b$12$uL8suHT0HDPMmiiwiQnsWOurBsBC5UY7zBmaVcovyKk8Tdr3HMvGW"
    ludivine:
      email: ludivine@gmail.com
      name: Ludivine
      password: "$2b$12$uL8suHT0HDPMmiiwiQnsWOurBsBC5UY7zBmaVcovyKk8Tdr3HMvGW"
cookie:
  expiry_days: 30
  key: projectbrief
  name: steel_fist_cookie